name: Testes Automatizados

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar testes com Pytest
        run: pytest -v